### ISSUE TITLE
Low Volume

### ISSUE THREAD

**Issue by DotRawr1** [l-Nuril-l/Voice-Messages-Plugin-BetterDiscord#1]
Volume of messages is very quiet, much quieter than discord receives audio from my mic when talking in a vc. Is there an easy way to increase the volume before sending with the plugin?

**Comment by l-Nuril-l** [comment]
Add after line 132: `'-v', '2.0',`

**Comment by DotRawr1** [comment]
Worked perfectly, thanks!
