### ISSUE TITLE
Uploads 0-byte .wav instantly

### ISSUE THREAD

**Issue by 12Echo** [l-Nuril-l/Voice-Messages-Plugin-BetterDiscord#2]
When I press "Record voice message" it just instantly uploads a 0 byte 0:00 .wav file named "Voice_Message" and never records anything and when I press "End recording" nothing happens.

http://ss.jimmyfalcone.com/a29oa7k4.gif

**Comment by l-Nuril-l** [comment]
Install the dependency (sox).
In the plugin settings or manually to the folder: `plugins/soX`.
http://sourceforge.net/projects/sox/files/latest/download

**Comment by 12Echo** [comment]
> 

I have it installed to "BetterDiscord\plugins\soX"

**Comment by l-Nuril-l** [comment]
Can you post the error from the console?

**Comment by 12Echo** [comment]
> 

It doesn't seem to give me an error, just immediately uploads a blank file to their DM.

**Comment by l-Nuril-l** [comment]
https://user-images.githubusercontent.com/49325887/164152414-119111d6-fe06-4f4d-8235-2fc54423e780.mp4

**Comment by 12Echo** [comment]
> > 
> 
> It doesn't seem to give me an error, just immediately uploads a blank file to their DM.

I got it to work by using a slightly older version of sox 👍

**Comment by l-Nuril-l** [comment]
🎉
You probably didn't restart discord and that's why the new version didn't work.

**Comment by SmilerRyan** [comment]
> I got it to work by using a slightly older version of sox 👍

My I ask which version of SoX are you using? I'm having the same issue on Windows x64.

**Comment by l-Nuril-l** [comment]
@SmilerRyan What error in the console?

If you have the error from the video above.
Did you do a FULL restart of BetterDicord after installing SOX?

Also, if you have manually installed SOX, check -> https://github.com/l-Nuril-l/Voice-Messages-Plugin-BetterDiscord#editing-environment-variables-windows.
and restart it again.
