### ISSUE TITLE
Plugin isn't working

### ISSUE THREAD

**Issue by N1lzh** [l-Nuril-l/Voice-Messages-Plugin-BetterDiscord#3]
Hi,
I've found your Plugin and it seemed really good.
Sadly it's not working really good. Whenever I want to record a voice message it just sends it immediatly, leaving a zero second long .wav file in the channel.
I know the plugin is a few months old by now but I would appreciate a fix.
I'm looking forward for a respond, attached you will find what the file looks like :)
![image](https://user-images.githubusercontent.com/61562307/175086735-b4f6e857-0be9-499f-96e7-943e8a51931e.png)

**Comment by FQQD** [comment]
I also have the same problem. I installed soX with the provided command (i'm on linux) and it does the same thing for me.

**Comment by l-Nuril-l** [comment]
The plugin still works, maybe you forgot to change the Sox installation path.
If not, send an error from the console.

Also check this -> https://github.com/l-Nuril-l/Voice-Messages-Plugin-BetterDiscord/issues/2
![image](https://user-images.githubusercontent.com/49325887/175201696-782c8965-42bd-443a-af78-6f0078e51fe0.png)

**Comment by Xenonus** [comment]
> I also have the same problem. I installed soX with the provided command (i'm on linux) and it does the same thing for me.

Same

**Comment by l-Nuril-l** [comment]
No feedback
