### ISSUE TITLE
[Suggestion] Recreate the plugin for 2024

### ISSUE THREAD

**Issue by Setnour6** [l-Nuril-l/Voice-Messages-Plugin-BetterDiscord#7]
I found that people can send voice messages on the discord desktop client through the use of the Vencord plugin titled `VoiceMessages` just like how mobile users can do so. I simply ask if you can recreate something like that for BetterDiscord. You or I can also ask other people to have it made or collaborated upon as well.

Link to Vencord plugin in question: [https://vencord.dev/plugins/VoiceMessages](https://vencord.dev/plugins/VoiceMessages)

**Comment by l-Nuril-l** [comment]
I switched to Vencord over a year ago.
P.S. Vencord, unlike BetterDiscord, does not lag at all. I recommend.

**Comment by Setnour6** [comment]
I tried Vencord but I haven't got all of the plugins there, and some plugins that have been requested for months aren't available. I can keep waiting or ask the contributors about how plugin development is. I'll close this issue since this answers my suggestion.

**Comment by l-Nuril-l** [comment]
New version v1.1.0 available.
Check README.
